/**
 * 全局类型定义入口
 * 后端联调时：字段名尽量与 Java DTO 保持一致，避免前后端命名漂移
 */

export type {
  User,
  LoginPayload,
  RegisterPayload,
  AuthResponse,
  RefreshResponse,
  MeResponse,
} from './auth'
export type {
  Team,
  TeamRole,
  TeamMember,
  CreateTeamPayload,
  CreateInvitationPayload,
  TeamInvitation,
  AcceptInvitationResponse,
} from './team'
export type { Project, ProjectRole, ProjectMember, CreateProjectPayload } from './project'
export type {
  Agent,
  AgentAvailability,
  AgentDetail,
  AgentDetailTab,
  AgentPermissions,
  AgentPresentation,
  AgentRole,
  AgentRoleTag,
  AgentRunRecord,
  AgentSkillBinding,
  AgentSkillBindingResponse,
  AgentSummary,
  AgentVisibility,
  AgentRuntimeStatus,
  AgentRuntimeSummary,
  AgentAssignmentUsage,
  AgentAssignmentType,
  AgentAssignmentSummary,
  AgentTaskRunSummary,
  CreateAgentPayload,
  ProjectSkillOption,
  UpdateAgentPayload,
} from './agent'
export type {
  Group,
  GroupMember,
  Message,
  MessageSummary,
  MessageContentType,
  MessageSenderType,
  TextMessageContent,
  CodeMessageContent,
  ImageMessageContent,
  FileMessageContent,
  QuoteMessageContent,
  DiffMessageContent,
  TaskStatusMessageContent,
  SystemMessageContent,
  SendMessagePayload,
  CreateGroupPayload,
  Page,
} from './group'
export type {
  TaskRepository,
  WorkflowRole,
  CreateTaskPayload,
} from './task'
export type { Notification, NotificationKind } from './notification'
export type {
  BranchHealthStatus,
  BranchTestStatus,
  BranchRelatedTask,
  ProjectBranchRow,
} from './codeBranch'
export type {
  DiffReviewStatus,
  DiffFileStatus,
  DiffLineKind,
  DiffCommentSide,
  DiffLine,
  DiffHunk,
  DiffReviewView,
} from './diff'
export type {
  Memory,
  MemoryStatus,
  MemorySourceType,
  MemorySourceRef,
  MemoryActor,
  CreateMemoryPayload,
  GenerateMemoryDraftPayload,
} from './memory'
export type {
  Skill,
  SkillStatus,
  SkillVisibility,
  SkillActor,
  CreateSkillPayload,
} from './skill'
export type {
  GithubInstallation,
  GithubInstallationRedirect,
  GithubAuthorizedRepository,
  ProjectBoundRepository,
  BindProjectRepositoryPayload,
} from './github'
export type {
  Task,
  TaskListItem,
  TaskRequirementGroupSummary,
  TaskUserSummary,
  TaskRepositorySummary,
  TaskExecutionSummary,
  TaskAttention,
  TaskAttentionKind,
  TaskAcceptanceCriterion,
  TaskWorkspace,
  TaskCapabilities,
  TaskArtifactSummary,
  TaskDiffReviewSummary,
  TaskSourceMessage,
  TaskStatus,
  TaskStep,
  TaskStepCreateInput,
  ReplaceTaskStepAgentInput,
  TaskStepStatus,
  TaskStepRole,
  TaskRun,
  TaskRunSummary,
  TaskRunDetail,
  TaskRunStatus,
  TaskRunStep,
  TaskRunStepStatus,
  TaskRunLog,
  ExecutionContext,
  SandboxStatus,
  InputRequest,
  InputRequestOption,
  InputRequestKind,
  InputRequestStatus,
  DiffStatus,
  DiffListItem,
  DiffDetail,
  DiffChangeStats,
  DiffFile,
  DiffComment,
  DiffCommentInput,
  DiffListFilters,
  DiffRejectInput,
  TaskCreateInput,
  TaskListFilters,
  TaskRunListFilters,
  PageFilters,
  TaskModelPage,
  InputRequestAnswer,
  InputRequestDecision,
  TaskArtifact,
  TaskArtifactType,
  DiffReviewDeliveryStatus,
  DiffReviewBatch,
} from './task-model'
export type { ApiErrorDetail, ApiErrorResponse, ApiResponse, CursorPage } from './api'
export type {
  CodeDeliveryItem,
  CodeDeliveryStatus,
  CodeRepositoryDelivery,
  CodeReviewStatus,
  DeliveryAction,
  DeliveryActionInput,
  DeliveryActor,
  DeliveryCapabilities,
  DeliveryCountsByType,
  DeliveryDisplayStatus,
  DeliveryItem,
  DeliveryItemsFilters,
  DeliveryItemsResponse,
  DeliveryMergeRequestSummary,
  DeliveryRepositorySummary,
  DeliveryRepositoryRef,
  DeliveryRequirementGroup,
  DeliveryRequirementGroupSummary,
  DeliveryResourceType,
  DeliverySource,
  DeliveryStatusCounts,
  DeliverySummary,
  DeliverySummaryFilters,
  MemoryDeliveryItem,
  MemorySource,
  SkillDeliveryItem,
} from './delivery-center'
