import { render, screen, waitFor } from '@testing-library/react'
import userEvent from '@testing-library/user-event'
import { MemoryRouter, Route, Routes, useLocation } from 'react-router-dom'
import { beforeEach, describe, expect, it, vi } from 'vitest'
import { ApiError } from '@/api'
import type { Task, TaskModelPage, TaskRunDetail, TaskStep } from '@/types/task-model'

const useTaskMock = vi.hoisted(() => vi.fn()); const useTaskRunMock = vi.hoisted(() => vi.fn()); const useTaskStepsMock = vi.hoisted(() => vi.fn()); const useLogsMock = vi.hoisted(() => vi.fn()); const useContextMock = vi.hoisted(() => vi.fn()); const useRequestsMock = vi.hoisted(() => vi.fn()); const useRetryMock = vi.hoisted(() => vi.fn()); const useCancelMock = vi.hoisted(() => vi.fn()); const useReplyMock = vi.hoisted(() => vi.fn()); const useApproveMock = vi.hoisted(() => vi.fn()); const useRejectMock = vi.hoisted(() => vi.fn())
vi.mock('@/hooks/task-model', () => ({ useTask: useTaskMock, useTaskRun: useTaskRunMock, useTaskSteps: useTaskStepsMock, useTaskRunLogs: useLogsMock, useTaskRunExecutionContext: useContextMock, useTaskRunInputRequests: useRequestsMock, useRetryTaskRunModel: useRetryMock, useCancelTaskRunModel: useCancelMock, useReplyTaskRunInputRequest: useReplyMock, useApproveTaskRunInputRequest: useApproveMock, useRejectTaskRunInputRequest: useRejectMock }))

import { TaskRunDetailPage } from './TaskRunDetailPage'

const task: Task = { id: 'task-1', projectId: 'project-test', requirementGroupId: 'group-1', triggerMessageId: 'message-1', title: '执行任务', requirement: '需求', status: 'RUNNING', workspaceId: 'workspace-1', workspaceStatus: 'READY', continuationOfTaskId: null, repositoryIds: ['repo-1'], repositories: [], createdBy: 'user-1', createdAt: '2026-08-11T08:00:00Z', updatedAt: '2026-08-11T08:30:00Z' }
const step: TaskStep = { id: 'step-1', taskId: 'task-1', role: 'DEVELOPER', agentId: 'agent-1', repositoryId: 'repo-1', baseRef: 'main', dependencies: [], testsetIds: [], status: 'RUNNING', acceptanceNotes: null }
const run: TaskRunDetail = { id: 'run-1', projectId: 'project-test', taskId: 'task-1', taskStepId: 'step-1', agentId: 'agent-1', role: 'DEVELOPER', status: 'WAITING_INPUT', retryOfTaskRunId: null, artifactSummary: { diffs: { count: 2, byStatus: { PENDING_REVIEW: 2 } } }, startedAt: '2026-08-11T08:00:00Z', finishedAt: null, durationMs: null, createdAt: '2026-08-11T08:00:00Z', updatedAt: '2026-08-11T08:30:00Z' }
function page<T>(data: T[]): TaskModelPage<T> { return { data, page: { nextCursor: null, hasMore: false }, requestId: 'request-1' } }
function renderPage(path = '/app/projects/project-test/tasks/task-1/executions/run-1') { return render(<MemoryRouter initialEntries={[path]}><Routes><Route path="/app/projects/:projectId/tasks/:taskId/executions/:taskRunId" element={<><TaskRunDetailPage /><LocationProbe /></>} /><Route path="/app/projects/:projectId/tasks/:taskId" element={<div>task-detail-route</div>} /></Routes></MemoryRouter>) }
function LocationProbe() { const location = useLocation(); return <output data-testid="location">{location.pathname}</output> }
beforeEach(() => { useTaskMock.mockReturnValue({ data: task, error: null, isError: false, isLoading: false }); useTaskRunMock.mockReturnValue({ data: run, error: null, isError: false, isLoading: false, refetch: vi.fn() }); useTaskStepsMock.mockReturnValue({ data: page([step]), error: null, isError: false, isLoading: false }); useLogsMock.mockReturnValue({ data: page([]), error: null, isError: false, isLoading: false }); useContextMock.mockReturnValue({ data: undefined, error: null, isError: false, isLoading: false }); useRequestsMock.mockReturnValue({ data: page([]), error: null, isError: false, isLoading: false }); const mutation = { mutate: vi.fn(), error: null, isPending: false }; useRetryMock.mockReturnValue(mutation); useCancelMock.mockReturnValue(mutation); useReplyMock.mockReturnValue(mutation); useApproveMock.mockReturnValue(mutation); useRejectMock.mockReturnValue(mutation) })

describe('TaskRunDetailPage', () => {
  it('uses taskId/taskRunId and validates run ownership', () => { renderPage(); expect(screen.getByRole('heading', { name: 'DEVELOPER' })).toBeInTheDocument(); expect(screen.getByText('2')).toBeInTheDocument(); expect(useTaskRunMock).toHaveBeenCalledWith('project-test', 'run-1'); expect(screen.getAllByText('暂无').length).toBeGreaterThan(0) })
  it('rejects a TaskRun that belongs to another task', () => { useTaskRunMock.mockReturnValue({ data: { ...run, taskId: 'task-other' }, error: null, isError: false, isLoading: false }); renderPage(); expect(screen.getByText('TaskRun 不属于当前任务或不可见')).toBeInTheDocument() })
  it('retries and navigates to the server-created run', async () => { const user = userEvent.setup(); const next = { ...run, id: 'run-2', status: 'QUEUED' as const, retryOfTaskRunId: run.id }; useTaskRunMock.mockReturnValue({ data: { ...run, status: 'FAILED' as const }, error: null, isError: false, isLoading: false }); const mutate = vi.fn((_id: string, options: { onSuccess: (value: TaskRunDetail) => void }) => options.onSuccess(next)); useRetryMock.mockReturnValue({ mutate, error: null, isPending: false }); vi.spyOn(window, 'confirm').mockReturnValue(true); renderPage(); await user.click(screen.getByRole('button', { name: /重\s*试/ })); await waitFor(() => expect(screen.getByTestId('location')).toHaveTextContent('executions/run-2')) })
  it('isolates logs, context, input request failures and uses optional steps', () => { useTaskRunMock.mockReturnValue({ data: { ...run, steps: undefined }, error: null, isError: false, isLoading: false }); useLogsMock.mockReturnValue({ data: undefined, error: new ApiError('logs', 500), isError: true, isLoading: false }); useContextMock.mockReturnValue({ data: undefined, error: new ApiError('context', 500), isError: true, isLoading: false }); useRequestsMock.mockReturnValue({ data: undefined, error: new ApiError('requests', 500), isError: true, isLoading: false }); renderPage(); expect(screen.getByText('Logs加载失败')).toBeInTheDocument(); expect(screen.getByText('Execution Context加载失败')).toBeInTheDocument(); expect(screen.getByText('Input Requests加载失败')).toBeInTheDocument(); expect(screen.getByText('暂无执行步骤')).toBeInTheDocument() })
})
