import { render, screen, waitFor } from '@testing-library/react'
import userEvent from '@testing-library/user-event'
import { MemoryRouter, Route, Routes, useLocation } from 'react-router-dom'
import { beforeEach, describe, expect, it, vi } from 'vitest'
import { ApiError } from '@/api'
import type { Task, TaskModelPage, TaskRunDetail, TaskStep } from '@/types/task-model'

const useTaskMock = vi.hoisted(() => vi.fn()); const useTaskRunMock = vi.hoisted(() => vi.fn()); const useTaskStepsMock = vi.hoisted(() => vi.fn()); const useLogsMock = vi.hoisted(() => vi.fn()); const useContextMock = vi.hoisted(() => vi.fn()); const useRequestsMock = vi.hoisted(() => vi.fn()); const useRetryMock = vi.hoisted(() => vi.fn()); const useCancelMock = vi.hoisted(() => vi.fn()); const useReplyMock = vi.hoisted(() => vi.fn()); const useApproveMock = vi.hoisted(() => vi.fn()); const useRejectMock = vi.hoisted(() => vi.fn())
vi.mock('@/hooks/task-model', () => ({ useTask: useTaskMock, useTaskRun: useTaskRunMock, useTaskSteps: useTaskStepsMock, useTaskRunLogs: useLogsMock, useTaskRunExecutionContext: useContextMock, useTaskRunInputRequests: useRequestsMock, useRetryTaskRunModel: useRetryMock, useCancelTaskRunModel: useCancelMock, useReplyTaskRunInputRequest: useReplyMock, useApproveTaskRunInputRequest: useApproveMock, useRejectTaskRunInputRequest: useRejectMock }))

import { TaskRunDetailPage } from './TaskRunDetailPage'

const task: Task = { id: 'task-1', displayCode: 'T-1', projectId: 'project-test', title: '执行任务', requirementSummary: '需求', status: 'RUNNING', deliveryMode: 'DIFF_FIRST', requirementGroup: { id: 'group-1', name: 'Group', status: 'ACTIVE' }, createdByUser: { id: 'user-1', displayName: 'User', avatarUrl: null }, repositories: [], executionSummary: { totalSteps: 1, pendingSteps: 0, runningSteps: 1, waitingSteps: 0, blockedSteps: 0, succeededSteps: 0, failedSteps: 0, currentStage: 'DEVELOPER', currentStageTitle: 'Developer', requiresUserAction: false }, attention: null, createdAt: '2026-08-11T08:00:00Z', updatedAt: '2026-08-11T08:30:00Z', requirement: '需求', acceptanceCriteria: [], workspace: null, capabilities: { canCancel: true, canReplacePendingStepAgent: false, canConfirmDiffReview: false, canRejectDiffReview: false, canRetryDelivery: false }, artifactSummary: { total: 0, byType: {} }, diffReviewSummary: { available: false, reviewStatus: null, deliveryStatus: null, repositoryCount: 0, filesChanged: 0, additions: 0, deletions: 0 }, sourceMessage: null, triggerMessageId: null }
const step: TaskStep = { id: 'step-1', taskId: 'task-1', sequenceNo: 1, title: 'Developer', description: null, role: 'DEVELOPER', agent: { id: 'agent-1', name: 'Agent', role: 'DEVELOPER', avatarUrl: null, status: 'ACTIVE' }, repository: null, dependencies: [], status: 'RUNNING', acceptanceNotes: null, latestRun: null, runCount: 1, startedAt: null, finishedAt: null, createdAt: '2026-08-11T08:00:00Z', updatedAt: '2026-08-11T08:30:00Z' }
const run: TaskRunDetail = { id: 'run-1', taskId: 'task-1', taskStepId: 'step-1', taskStepTitle: 'Developer', agent: null, role: 'DEVELOPER', status: 'WAITING_INPUT', retryOfTaskRunId: null, statusSummary: 'Waiting', statusReason: { code: 'INPUT_REQUIRED', title: 'Input', summary: 'Need input', retryable: false, occurredAt: '2026-08-11T08:00:00Z' }, startedAt: '2026-08-11T08:00:00Z', finishedAt: null, durationMs: null, artifactSummary: { total: 2, diffCount: 2 }, createdAt: '2026-08-11T08:00:00Z', updatedAt: '2026-08-11T08:30:00Z' }
function page<T>(data: T[]): TaskModelPage<T> { return { data, page: { nextCursor: null, hasMore: false }, requestId: 'request-1' } }
function renderPage(path = '/app/projects/project-test/tasks/task-1/executions/run-1') { return render(<MemoryRouter initialEntries={[path]}><Routes><Route path="/app/projects/:projectId/tasks/:taskId/executions/:taskRunId" element={<><TaskRunDetailPage /><LocationProbe /></>} /><Route path="/app/projects/:projectId/tasks/:taskId" element={<div>task-detail-route</div>} /><Route path="/app/projects/:projectId/diffs" element={<LocationProbe />} /></Routes></MemoryRouter>) }
function LocationProbe() { const location = useLocation(); return <output data-testid="location">{location.pathname}{location.search}</output> }
beforeEach(() => { useTaskMock.mockReturnValue({ data: task, error: null, isError: false, isLoading: false }); useTaskRunMock.mockReturnValue({ data: run, error: null, isError: false, isLoading: false, refetch: vi.fn() }); useTaskStepsMock.mockReturnValue({ data: page([step]), error: null, isError: false, isLoading: false }); useLogsMock.mockReturnValue({ data: page([]), error: null, isError: false, isLoading: false }); useContextMock.mockReturnValue({ data: undefined, error: null, isError: false, isLoading: false }); useRequestsMock.mockReturnValue({ data: page([]), error: null, isError: false, isLoading: false }); const mutation = { mutate: vi.fn(), error: null, isPending: false }; useRetryMock.mockReturnValue(mutation); useCancelMock.mockReturnValue(mutation); useReplyMock.mockReturnValue(mutation); useApproveMock.mockReturnValue(mutation); useRejectMock.mockReturnValue(mutation) })

describe('TaskRunDetailPage', () => {
  it('uses taskId/taskRunId and validates run ownership', () => { renderPage(); expect(screen.getByRole('heading', { name: 'DEVELOPER' })).toBeInTheDocument(); expect(screen.getByText('2')).toBeInTheDocument(); expect(useTaskRunMock).toHaveBeenCalledWith('project-test', 'run-1'); expect(screen.getAllByText('暂无').length).toBeGreaterThan(0) })
  it('rejects a TaskRun that belongs to another task', () => { useTaskRunMock.mockReturnValue({ data: { ...run, taskId: 'task-other' }, error: null, isError: false, isLoading: false }); renderPage(); expect(screen.getByText('TaskRun 不属于当前任务或不可见')).toBeInTheDocument() })
  it('retries and navigates to the server-created run', async () => { const user = userEvent.setup(); const next = { ...run, id: 'run-2', status: 'QUEUED' as const, retryOfTaskRunId: run.id }; useTaskRunMock.mockReturnValue({ data: { ...run, status: 'FAILED' as const }, error: null, isError: false, isLoading: false }); const mutate = vi.fn((_id: string, options: { onSuccess: (value: TaskRunDetail) => void }) => options.onSuccess(next)); useRetryMock.mockReturnValue({ mutate, error: null, isPending: false }); vi.spyOn(window, 'confirm').mockReturnValue(true); renderPage(); await user.click(screen.getByRole('button', { name: /重\s*试/ })); await waitFor(() => expect(screen.getByTestId('location')).toHaveTextContent('executions/run-2')) })
  it('isolates logs, context, input request failures and uses optional steps', () => { useTaskRunMock.mockReturnValue({ data: { ...run, steps: undefined }, error: null, isError: false, isLoading: false }); useLogsMock.mockReturnValue({ data: undefined, error: new ApiError('logs', 500), isError: true, isLoading: false }); useContextMock.mockReturnValue({ data: undefined, error: new ApiError('context', 500), isError: true, isLoading: false }); useRequestsMock.mockReturnValue({ data: undefined, error: new ApiError('requests', 500), isError: true, isLoading: false }); renderPage(); expect(screen.getByText('Logs加载失败')).toBeInTheDocument(); expect(screen.getByText('Execution Context加载失败')).toBeInTheDocument(); expect(screen.getByText('Input Requests加载失败')).toBeInTheDocument(); expect(screen.getByText('暂无执行步骤')).toBeInTheDocument() })
  it('navigates from a TaskRun to the task-filtered Diff Center', async () => { const user = userEvent.setup(); renderPage(); await user.click(screen.getByRole('button', { name: /Diff/ })); expect(screen.getByTestId('location')).toHaveTextContent('/app/projects/project-test/diffs?taskId=task-1') })
})
